export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import React from 'react'
import './globals.css'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <main className="bg-slate-500 w-full h-full min-h-screen flex justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  )
}
